### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by PBarmby** [mshubat/galaxy_data_mines#2]
You've listed Python 3.7 in the "tech" section of the README - should the versions of the various other packages (Astropy etc) be listed?

**Comment by mshubat** [comment]
Yes this is an inconsistency. 

Recently with the commit ["Divide by 0, README, Automatic Dependencies"](https://github.com/mshubat/galaxy_data_mines/commit/ef8ff7b6302cf0b6d09ba14af5d25d9e10c6e849)

I changed the setup.py file to automatically install any missing packages that are required. The packages which are fetched and installed by pip will be the latest packages.

So perhaps changing the versions to (Latest) on each would be sufficient for now?
