### ISSUE TITLE
options for byname command don't seem to work

### ISSUE THREAD

**Issue by PBarmby** [mshubat/galaxy_data_mines#3]
Maybe I just haven't figured out the syntax - working on that now.

Error messages with various variations:
gdmines byname -obj_radius 3.0 "NGC300"
Usage: gdmines byname [OPTIONS] NAME
Try "gdmines byname --help" for help.

Error: no such option: -o

gdmines byname obj_radius 3.0 "NGC300"
Usage: gdmines byname [OPTIONS] NAME
Try "gdmines byname --help" for help.

Error: Got unexpected extra arguments (3.0 NGC300)

gdmines byname --obj_radius 3.0 "NGC300"
Usage: gdmines byname [OPTIONS] NAME
Try "gdmines byname --help" for help.

Error: no such option: --obj_radius

**Comment by PBarmby** [comment]
Never mind, I'm an idiot. Dash instead of underscore in obj-radius.

**Comment by mshubat** [comment]
Sorry, I just saw this. That may be a bit harsh of a judgement ha. Glad to see it worked out!
