### ISSUE TITLE
match_stats can throw a ZeroDivisionError

### ISSUE THREAD

**Issue by PBarmby** [mshubat/galaxy_data_mines#4]
If there are no NED or SIMBAD objects, or no matches between them, then division by zero is a possibility. This requires some simple error trapping which wouldn't be that hard to add if it wasn't Friday afternoon..

**Comment by mshubat** [comment]
Just added a quick patch, not sure if it totally addresses this issue. But I think it should work..

**Comment by PBarmby** [comment]
Tried it - seems to be OK.
